// <auto-generated />
using ExamFinalASPNETCOREMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamFinalASPNETCOREMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamFinalASPNETCOREMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Powerful laptop for work and entertainment",
                            Name = "Laptop",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-end smartphone with advanced features",
                            Name = "Smartphone",
                            Price = 699.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise-canceling headphones for immersive audio experience",
                            Name = "Headphones",
                            Price = 149.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "Futuristic backpack equipped with anti-gravity technology",
                            Name = "Rocket Backpack",
                            Price = 249.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            Description = "Magical cloak that renders the wearer invisible",
                            Name = "Invisibility Cloak",
                            Price = 599.99000000000001
                        },
                        new
                        {
                            Id = 6,
                            Description = "Levitating skateboard for an effortless commute",
                            Name = "Hoverboard",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 7,
                            Description = "AI-powered robotic butler for personalized assistance",
                            Name = "Robot Butler",
                            Price = 1999.99
                        },
                        new
                        {
                            Id = 8,
                            Description = "Immersive VR glasses for virtual adventures",
                            Name = "Virtual Reality Glasses",
                            Price = 299.99000000000001
                        },
                        new
                        {
                            Id = 9,
                            Description = "A self-refilling and infinitely warm bath inspired by Archimedes' principles",
                            Name = "Archimedes' Infinite Bath",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 10,
                            Description = "A pen that translates your thoughts into Shakespearean sonnets as you write",
                            Name = "Shakespearean Smart Pen",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 11,
                            Description = "Watch that lets you travel through time and explore different eras",
                            Name = "Time-Traveling Watch",
                            Price = 999.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
